### PR TITLE
remove suspicious taxonID values; related to https://github.com/njdow…

### PR DESCRIPTION
**Pull request by jhpoelen**
…dy/tpt-taxonomy/issues/18

please accept this pull request to remove non-unique taxoniDs for the mammalia-standardized-v2.csv .

### CODE REVIEW

**Comment by jhpoelen** [comment]
I've also added a patch to make taxonID prefixes for Acari consistent see https://github.com/njdowdy/tpt-taxonomy/issues/16 .

**Comment by EMTuckerLab** [comment]
Just want to check before merging - does this patch just remove the TaxonID duplicates? Or does it remove the whole row? The rows all appear to be different taxa - not sure why there are so many duplicate IDs. The ID numbers would be from the original file received from this project and I'm guessing the column was either miss-mapped or just incorrectly used/misunderstood...

**Comment by jhpoelen** [comment]
@EMTuckerLab thanks for checking! For the Mammalia taxonomy the taxonID are removed altogether: the taxonID column is still there, only the values are removed. On inspecting the taxonID values in Mammalia host taxonomy, I found many repetitions of the same four values (from https://github.com/njdowdy/tpt-taxonomy/issues/18#issue-1404769726)

```
 6369 220
   1328 180
    170 140
     27 100
```

and these value happen to align with values for the ```nomenclaturalCode``` field (see below). 


| source | taxonID | scientificNameID | acceptedNameUsageID | parentNameUsageID | originalNameUsageID | nameAccordingToID | namePublishedInID | taxonConceptID | scientificName | acceptedNameUsage | parentNameUsage | originalNameUsage | nameAccordingTo | namePublishedIn | namePublishedInYear | higherClassification | kingdom | phylum | class | subclass | superorder | order | suborder | infraorder | parvorder | nanorder | superfamily | family | subfamily | tribe | subtribe | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | taxonRank | verbatimTaxonRank | scientificNameAuthorship | vernacularName | nomenclaturalCode | taxonomicStatus | nomenclaturalStatus | taxonRemarks | canonicalName |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| ASM | 100 |  |  |  |  |  |  |  | Afrosoricida |  | Mammalia |  |  |  |  |  | Animalia | Chordata | Mammalia |  |  | Afrosoricida |  |  |  |  |  |  |  |  |  |  |  |  |  | order |  |  |  |  |  |  | 100 |   |
| ASM | 220 |  |  |  |  |  |  |  | Antilocapra americana |  | Antilocapra |  |  |  |  |  | Animalia | Chordata | Mammalia |  |  | Artiodactyla |  |  |  |  |  | Antilocapridae |  |  |  | Antilocapra |  | americana |  | species |  |  |  |  |  |  | 220 | Antilocapra americana |

**Comment by EMTuckerLab** [comment]
👍

**Comment by jhpoelen** [comment]
@EMTuckerLab thanks!

**Pull request merged**
